### ISSUE TITLE
Fail to fully reproduce the results on truthfulQA

### ISSUE THREAD

**Issue by CuSO4-Chen** [HillZhang1999/ICD#2]
Hi~Thanks for your excellent work! I'd like to bother you for a question that I'd like reproduce the results on truthfulQA by llama2-7b-chat-hf vs. untruthful-llama2-7b (which was provided), I followed the instrustions and got the results of MC1: 0.4607; MC2: 0.5383; MC3:0.3677, which are not consistent with the results from paper. What should I do for obtaining the exact results?

I am sincerely looking forward to your reply, thank you very much!

**Comment by HillZhang1999** [comment]
Sorry, I rerun the code and still can reproduce the results. Please provide more details about your reproduction.

**Comment by CuSO4-Chen** [comment]
ok, I run the code on the A800 * 1, the information of the truthfulqa.sh is as follows:

TS=$(date "+%Y%0m%0d_%T")

project_root_path="../../"
cli_path="${project_root_path}/src/benchmark_evaluation/truthfulqa_eval.py"
data_path="${project_root_path}/data/truthfulqa"

### Exps with Llama2-7B
model_name="/data/zoo/llama-2-7b-chat-hf"
amateur_model_name="/data/zoo/model/untruthful_llama2-7b"

# ### For experiments using Baichuan2
# model_name="baichuan-inc/Baichuan2-7B-Chat"
# amateur_model_name="HillZhang/untruthful_baichuan2_7b"

# ### For experiments using Mistral
# model_name="mistralai/Mistral-7B-Instruct-v0.1"
# amateur_model_name="HillZhang/untruthful_mistral_7b"

### Baseline
output_path="${project_root_path}/exp_results/truthfulqa/${TS}/Greedy_llama2_7b_chat"
mkdir -p $output_path
cp $0 "$(dirname "$output_path")"

generation_args="
    --relative_top 0.0
"

echo "Greedy Decoding"
for i in 6; do
    echo "devices: ${i}"
    CMD="CUDA_VISIBLE_DEVICES=$i nohup python ${cli_path}
        --model-name ${model_name} \
        --num-gpus 1 \
        --data-path ${data_path} \
        --output-path ${output_path}"/result" \
        --is-chat \
        --mode greedy \
        --parallel \
        --total-shard 8 \
        --shard-id $i \
        ${generation_args} \
        >${output_path}/shard_${i}.log 2>&1 &"
    echo $CMD
    eval $CMD
done
wait

### Our method
output_path="${project_root_path}/exp_results/truthfulqa/${TS}/ICD_llama2_7b_chat"
mkdir -p $output_path
cp $0 "$(dirname "$output_path")"

echo "ICD"
for i in 6; do
    echo "devices: ${i}"
    CMD="CUDA_VISIBLE_DEVICES=$i nohup python ${cli_path}
        --model-name ${model_name} \
        --amateur-model-name ${amateur_model_name} \
        --num-gpus 1 \
        --amateur-model-nums-gpus 1 \
        --data-path ${data_path} \
        --output-path ${output_path}"/result" \
        --is-chat \
        --mode contrastive-decoding \
        --parallel \
        --total-shard 8 \
        --shard-id $i \
        ${generation_args} \
        >${output_path}/shard_${i}.log 2>&1 &"
    echo $CMD
    eval $CMD

done
wait

**Comment by CuSO4-Chen** [comment]
ok, I run the code on the A800 * 1, the information of the truthfulqa.sh is as follows:

output_path="${project_root_path}/exp_results/truthfulqa/${TS}/Greedy_llama2_7b_chat"
mkdir -p $output_path
cp $0 "$(dirname "$output_path")"

generation_args="
    --relative_top 0.0
"

echo "Greedy Decoding"
for i in 6; do
    echo "devices: ${i}"
    CMD="CUDA_VISIBLE_DEVICES=$i nohup python ${cli_path}
        --model-name ${model_name} \
        --num-gpus 1 \
        --data-path ${data_path} \
        --output-path ${output_path}"/result" \
        --is-chat \
        --mode greedy \
        --parallel \
        --total-shard 8 \
        --shard-id $i \
        ${generation_args} \
        >${output_path}/shard_${i}.log 2>&1 &"
    echo $CMD
    eval $CMD
done
wait

### Our method
output_path="${project_root_path}/exp_results/truthfulqa/${TS}/ICD_llama2_7b_chat"
mkdir -p $output_path
cp $0 "$(dirname "$output_path")"

echo "ICD"
for i in 6; do
    echo "devices: ${i}"
    CMD="CUDA_VISIBLE_DEVICES=$i nohup python ${cli_path}
        --model-name ${model_name} \
        --amateur-model-name ${amateur_model_name} \
        --num-gpus 1 \
        --amateur-model-nums-gpus 1 \
        --data-path ${data_path} \
        --output-path ${output_path}"/result" \
        --is-chat \
        --mode contrastive-decoding \
        --parallel \
        --total-shard 8 \
        --shard-id $i \
        ${generation_args} \
        >${output_path}/shard_${i}.log 2>&1 &"
    echo $CMD
    eval $CMD

done
wait

**Comment by HillZhang1999** [comment]
You seems like only evaluate `shard 6` of truthfulqa by only set i to 6, please change your script.

**Comment by CuSO4-Chen** [comment]
Oh, I misunderstand it as the number only for device, I will try it, thank you every much!

**Comment by AlmightYouth** [comment]
> Sorry, I rerun the code and still can reproduce the results. Please provide more details about your reproduction.

Thank you for your outstanding work, and I apologize for the interruption. I am encountering the same issue as him, in that I am unable to reproduce your experimental results. I have reviewed his issue, but it seems that we are not encountering the same error. I would like to kindly ask if you could take a look at my script to check if the problem lies within it.

I am running it on an A100-80G GPU, using the llama2-7b-chat-hf model in comparison with the untruthful-llama2-7b model you provided. Here is my script:

### Baseline
# output_path="${project_root_path}/exp_results/truthfulqa/${TS}/Greedy_llama2_7b_chat"
# mkdir -p $output_path
# cp $0 "$(dirname "$output_path")"

generation_args="
--relative_top 0.0
"

# echo "Greedy Decoding"
# for i in 0; do
#     echo "devices: ${i}"
#     CMD="CUDA_VISIBLE_DEVICES=$i nohup python ${cli_path}
#         --model-name ${model_name} \
#         --num-gpus 1 \
#         --data-path ${data_path} \
#         --output-path ${output_path}"/result" \
#         --is-chat \
#         --mode greedy \
#         --parallel \
#         --total-shard 8 \
#         --shard-id $i \
#         ${generation_args} \
#         >${output_path}/shard_${i}.log 2>&1 &"
#     echo $CMD
#     eval $CMD
# done
# wait

# Our method
output_path="${project_root_path}/exp_results/truthfulqa/${TS}/ICD_llama2_7b_chat"
mkdir -p $output_path
cp $0 "$(dirname "$output_path")"

echo "ICD"
for i in 0; do
    echo "devices: ${i}"
    CMD="CUDA_VISIBLE_DEVICES=$i nohup python ${cli_path}
        --model-name ${model_name} \
        --amateur-model-name ${amateur_model_name} \
        --num-gpus 1 \
        --amateur-model-nums-gpus 1 \
        --data-path ${data_path} \
        --output-path ${output_path}"/result" \
        --is-chat \
        --mode contrastive-decoding \
        --total-shard 1 \
        --shard-id $i \
        ${generation_args} \
        >${output_path}/shard_${i}.log 2>&1 &"
    echo $CMD
    eval $CMD

done
wait

Thank you very much for taking the time to assist me, and I look forward to your valuable feedback.

**Comment by AlmightYouth** [comment]
Thank you for your outstanding work, and I apologize for the interruption. I am encountering the same issue as him, in that I am unable to fully reproduce your experimental results.I got the result: MC1 40.26 MC2 69.72 MC3 41.13. I have reviewed his issue, but it seems that we are not encountering the same error. I would like to kindly ask if you could take a look at my script to check if the problem lies within it.

I am running it on an A100-80G GPU, using the llama2-7b-chat-hf model in comparison with the untruthful-llama2-7b model you provided. Here is my script,:
generation_args="
--relative_top 0.0
"

output_path="${project_root_path}/exp_results/truthfulqa/${TS}/ICD_llama2_7b_chat"
mkdir -p $output_path
cp $0 "$(dirname "$output_path")"

echo "ICD"
for i in 0; do
    echo "devices: ${i}"
    CMD="CUDA_VISIBLE_DEVICES=$i nohup python ${cli_path}
        --model-name ${model_name} \
        --amateur-model-name ${amateur_model_name} \
        --num-gpus 1 \
        --amateur-model-nums-gpus 1 \
        --data-path ${data_path} \
        --output-path ${output_path}"/result" \
        --is-chat \
        --mode contrastive-decoding \
        --total-shard 1 \
        --shard-id $i \
        ${generation_args} \
        >${output_path}/shard_${i}.log 2>&1 &"
    echo $CMD
    eval $CMD

done
wait

Thank you very much for taking the time to assist me, and I look forward to your valuable feedback.

**Comment by AlmightYouth** [comment]
> Sorry, I rerun the code and still can reproduce the results. Please provide more details about your reproduction.

Thank you for your outstanding work, and I apologize for the interruption. I am encountering the same issue as him, in that I am unable to fully reproduce your experimental results.I got the result: MC1 40.26 MC2 69.72 MC3 41.13. I have reviewed his issue, but it seems that we are not encountering the same error. I would like to kindly ask if you could take a look at my script to check if the problem lies within it.

I am running it on an A100-80G GPU, using the llama2-7b-chat-hf model in comparison with the untruthful-llama2-7b model you provided. Here is my script,(I have omitted the Greedy Decoding part):
generation_args="
--relative_top 0.0
"

output_path="${project_root_path}/exp_results/truthfulqa/${TS}/ICD_llama2_7b_chat"
mkdir -p $output_path
cp 
0
"
(dirname "$output_path")"

echo "ICD"
for i in 0; do
echo "devices: ${i}"
CMD="CUDA_VISIBLE_DEVICES=$i nohup python ${cli_path}
--model-name ${model_name}
--amateur-model-name ${amateur_model_name}
--num-gpus 1
--amateur-model-nums-gpus 1
--data-path ${data_path}
--output-path ${output_path}"/result"
--is-chat
--mode contrastive-decoding
--total-shard 1
--shard-id $i
${generation_args}
>${output_path}/shard_${i}.log 2>&1 &"
echo $CMD
eval $CMD

done
wait

Thank you very much for taking the time to assist me, and I look forward to your valuable feedback.
